# Generated by Django 5.2.6 on 2025-12-17 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='time',
        ),
        migrations.AddField(
            model_name='tag',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
